import {
  Terminal,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  KeyRound,
  FileCode,
  Binary,
  Cpu,
  HardDrive,
  Server,
  Database,
  Network,
  Globe,
  Activity,
  Eye,
  EyeOff,
  FlaskConical,
  Droplet,
  Flame,
  Sparkles,
  Zap,
  Dna,
  HeartPulse,
  Microscope,
  Atom,
  Syringe,
  Radio,
  Tv,
  Wifi,
  WifiOff,
  Satellite,
  Antenna,
  Cable,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Component,
  Layers,
  Settings,
  Wrench,
  Hammer,
  Scissors,
  Lightbulb,
  Truck,
  Package,
  Box,
  MapPin,
  Compass,
  Navigation,
  Map,
  Anchor,
  Plane,
  Ship,
  ShoppingBag,
  Tag,
  QrCode,
  Barcode,
  Coins,
  DollarSign,
  Euro,
  CreditCard,
  Wallet,
  Briefcase,
  Scale,
  FileText,
  Layers3,
  UserCheck,
  Users,
  Share2,
  ExternalLink,
  LockKeyhole,
  Ghost,
  Skull,
  Bug,
  Search,
  HelpCircle,
  Info,
  AlertTriangle,
  Command,
  Fingerprint,
  MousePointer,
  Radar,
  TrendingUp,
  LineChart,
  GitBranch,
  ArrowRight,
  ChevronRight,
  Grid,
  List,
  FolderOpen,
  Power,
  MessageSquare,
  History,
  Disc,
  Volume2,
  Heart,
  LockKeyholeOpen,
  Folder,
  Play,
  Sliders,
  X,
} from "lucide-react";

export interface CategoryNode {
  id: string;
  label: string;
  iconName?: string;
  items?: CategoryNode[];
}

export const ICON_MAP: Record<string, any> = {
  Terminal,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  KeyRound,
  FileCode,
  Binary,
  Cpu,
  HardDrive,
  Server,
  Database,
  Network,
  Globe,
  Activity,
  Eye,
  EyeOff,
  FlaskConical,
  Droplet,
  Flame,
  Sparkles,
  Zap,
  Dna,
  HeartPulse,
  Microscope,
  Atom,
  Syringe,
  Radio,
  Tv,
  Wifi,
  WifiOff,
  Satellite,
  Antenna,
  Cable,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Component,
  Layers,
  Settings,
  Wrench,
  Hammer,
  Scissors,
  Lightbulb,
  Truck,
  Package,
  Box,
  MapPin,
  Compass,
  Navigation,
  Map,
  Anchor,
  Plane,
  Ship,
  ShoppingBag,
  Tag,
  QrCode,
  Barcode,
  Coins,
  DollarSign,
  Euro,
  CreditCard,
  Wallet,
  Briefcase,
  Scale,
  FileText,
  Layers3,
  UserCheck,
  Users,
  Share2,
  ExternalLink,
  LockKeyhole,
  Ghost,
  Skull,
  Bug,
  Search,
  HelpCircle,
  Info,
  AlertTriangle,
  Command,
  Fingerprint,
  MousePointer,
  Radar,
  TrendingUp,
  LineChart,
  GitBranch,
  ArrowRight,
  ChevronRight,
  Grid,
  List,
  FolderOpen,
  Power,
  MessageSquare,
  History,
  Disc,
  Volume2,
  Heart,
  LockKeyholeOpen,
  Folder,
  Play,
  Sliders,
  X,
};

export const DEFAULT_CATEGORY_TREE: CategoryNode[] = [
  {
    id: "DIGITAL",
    label: "DİJİTAL VARLIKLAR // DIGITAL",
    iconName: "FileCode",
    items: [
      {
        id: "CYBER_SECURITY",
        label: "Siber Güvenlik & Kod",
        iconName: "Terminal",
        items: [
          {
            id: "EXPLOIT_PAYLOADS",
            label: "Exploit & Güvenlik Yamaları",
            iconName: "Bug",
          },
          {
            id: "PENETRATION_KITS",
            label: "Sızma Test Yazılım Paketleri",
            iconName: "KeyRound",
          },
          {
            id: "ZERO_DAY_REPORTS",
            label: "Güvenlik Açığı Raporları",
            iconName: "ShieldAlert",
          },
        ],
      },
      {
        id: "DATA_LEAKS",
        label: "İstihbarat & Veritabanları",
        iconName: "Database",
        items: [
          {
            id: "OSINT_COLLECTIONS",
            label: "OSINT Kamu Dizinleri",
            iconName: "Search",
          },
          {
            id: "FINANCIAL_LOGS",
            label: "Teknik Sistem Log Dökümleri",
            iconName: "FileText",
          },
          {
            id: "GOVERNMENT_ARCHIVES",
            label: "Kurumsal Kamu Veri Setleri",
            iconName: "Globe",
          },
        ],
      },
      {
        id: "NETWORKING_CRYPT",
        label: "Ağ & Şifreleme Çözümleri",
        iconName: "Network",
        items: [
          {
            id: "SOCKS5_PROXIES",
            label: "Socks5 Proxy & Tünelleme",
            iconName: "Shield",
          },
          {
            id: "VPN_ROUTING",
            label: "Özel Kriptolu VPN Hatları",
            iconName: "Lock",
          },
          {
            id: "PGP_CRYPTO",
            label: "PGP Anahtar Yönetimi & Yazılım",
            iconName: "Key",
          },
        ],
      },
    ],
  },
  {
    id: "PHYSICAL",
    label: "FİZİKSEL DONANIM // PHYSICAL",
    iconName: "HardDrive",
    items: [
      {
        id: "HARDWARE_HACKING",
        label: "Donanım Müdahale Cihazları",
        iconName: "Cpu",
        items: [
          {
            id: "SDR_RF_TRANSCEIVERS",
            label: "RF & SDR Alıcı-Verici Telsizler",
            iconName: "Radio",
          },
          {
            id: "USB_INJECTORS",
            label: "USB Protokol Enjektörleri",
            iconName: "Binary",
          },
          {
            id: "PROTO_ANALYSERS",
            label: "Bus Pirate & Protokol Analizör",
            iconName: "Component",
          },
        ],
      },
      {
        id: "COMMUNICATION_GEAR",
        label: "Güvenli Haberleşme Donanımları",
        iconName: "Radio",
        items: [
          {
            id: "EMF_SHIELDS",
            label: "Faraday Kafesi Sinyal Torbaları",
            iconName: "Zap",
          },
          {
            id: "MODDED_ANON_ROUTERS",
            label: "Modlu OpenWRT/Tor Routerlar",
            iconName: "Wifi",
          },
        ],
      },
    ],
  },
  {
    id: "STEALTH_LOGISTICS",
    label: "GİZLİLİK & LOJİSTİK // LOGISTICS",
    iconName: "Truck",
    items: [
      {
        id: "DEAD_DROP_LOCS",
        label: "Güvenli Dead-Drop Noktaları",
        iconName: "Globe",
        items: [
          {
            id: "GPS_DROP_COORDS",
            label: "Şifreli GPS Drop Lokasyonları",
            iconName: "MapPin",
          },
          {
            id: "DEAD_DROP_BOXES",
            label: "Kamufle Fiziksel Kilitli Kutular",
            iconName: "Box",
          },
        ],
      },
      {
        id: "STEALTH_PACKAGING",
        label: "Yanıltıcı Gizli Paketleme",
        iconName: "Package",
        items: [
          {
            id: "EMF_SHIELD_POUCH",
            label: "GPS Engelleyici Alüminyum Torba",
            iconName: "Radar",
          },
          {
            id: "DECOY_CONTAINERS",
            label: "Stealth Decoy Taşıma Kapları",
            iconName: "Anchor",
          },
        ],
      },
    ],
  },
  {
    id: "LAB_REAGENTS",
    label: "KİMYASALLAR & LABORATUVAR // LABS",
    iconName: "FlaskConical",
    items: [
      {
        id: "REAGENT_TESTS",
        label: "Kimyasal Reaktif Test Kitleri",
        iconName: "ShieldCheck",
        items: [
          {
            id: "REAGENT_TEST_KITS",
            label: "Saha Saflık Reaktif Test Kitleri",
            iconName: "FlaskConical",
          },
          {
            id: "ANALYTICAL_SCALES",
            label: "Mikrogram Analitik Hassas Terazi",
            iconName: "Scale",
          },
        ],
      },
      {
        id: "ORGANIC_SOLVENTS",
        label: "Ekstraksiyon & Sentez Çözücüleri",
        iconName: "FlaskConical",
        items: [
          {
            id: "INDUSTRIAL_ACETONE",
            label: "Susuz Aseton %99.8 (Anhydrous)",
            iconName: "Droplet",
          },
          {
            id: "ETHYL_ETHER",
            label: "Diyetil Eter (Stabilized)",
            iconName: "Flame",
          },
          {
            id: "DCM_SOLVENT",
            label: "Diklorometan (DCM) %99.9",
            iconName: "FlaskConical",
          },
        ],
      },
      {
        id: "LAB_GLASSWARE",
        label: "Laboratuvar Cam & Distilasyon",
        iconName: "Layers",
        items: [
          {
            id: "DISTILLATION_COLUMNS",
            label: "Fraksiyonel Distilasyon Kolonları",
            iconName: "Layers",
          },
          {
            id: "BOROSILICATE_FLASKS",
            label: "Borosilikat Dibi Yuvarlak Balonlar",
            iconName: "Disc",
          },
          {
            id: "VACUUM_PUMPS",
            label: "Diyaframlı Vakum Pompaları",
            iconName: "Power",
          },
        ],
      },
    ],
  },
  {
    id: "INFRASTRUCTURE",
    label: "ALTYAPI & SUNUCU // SERVERS",
    iconName: "Server",
    items: [
      {
        id: "BULLETPROOF_HOST",
        label: "Kurşun Geçirmez Barındırma",
        iconName: "Lock",
        items: [
          {
            id: "OFFSHORE_VPS",
            label: "Offshore Güvenli Sanal Sunucular",
            iconName: "Server",
          },
          {
            id: "BULLETPROOF_DEDICATED",
            label: "DMCA Korumalı Fiziksel Sunucu",
            iconName: "LockKeyhole",
          },
        ],
      },
      {
        id: "DECENTRALIZED_VPS",
        label: "Merkeziyetsiz Sunucu Ağları",
        iconName: "Network",
        items: [
          {
            id: "PEER_HOSTING",
            label: "Eşler Arası Güvenli Web Hosting",
            iconName: "Globe",
          },
          {
            id: "ANON_NODE_MGMT",
            label: "Yönetilen Tor & I2P Röle Node'ları",
            iconName: "Activity",
          },
        ],
      },
    ],
  },
];

export const CAT_ID_TO_KEY: Record<string, string> = {
  DIGITAL: "cat.digital",
  CYBER_SECURITY: "cat.cyber",
  EXPLOIT_PAYLOADS: "cat.exploits",
  PENETRATION_KITS: "cat.pents",
  ZERO_DAY_REPORTS: "cat.vulns",
  DATA_LEAKS: "cat.intel",
  OSINT_COLLECTIONS: "cat.osint",
  FINANCIAL_LOGS: "cat.logs",
  GOVERNMENT_ARCHIVES: "cat.sets",
  NETWORKING_CRYPT: "cat.crypt",
  SOCKS5_PROXIES: "cat.socks",
  VPN_ROUTING: "cat.vpn",
  PGP_CRYPTO: "cat.pgp",
  PHYSICAL: "cat.physical",
  HARDWARE_HACKING: "cat.hw_hack",
  SDR_RF_TRANSCEIVERS: "cat.rf",
  USB_INJECTORS: "cat.usb",
  PROTO_ANALYSERS: "cat.bus",
  COMMUNICATION_GEAR: "cat.secure_comm",
  EMF_SHIELDS: "cat.faraday",
  MODDED_ANON_ROUTERS: "cat.routers",
  PHYSICAL_BYPASS: "cat.bypass",
  LOCKPICK_TOOLS: "cat.lockpick",
  RFID_CLONERS: "cat.rfid",
  KEY_IMPRINTING: "cat.keys",
  STEALTH_LOGISTICS: "cat.logistics",
  DEAD_DROP_LOCS: "cat.drops",
  GPS_DROP_COORDS: "cat.gps",
  DEAD_DROP_BOXES: "cat.boxes",
  STEALTH_PACKAGING: "cat.packaging",
  EMF_SHIELD_POUCH: "cat.pouches",
  DECOY_CONTAINERS: "cat.containers",
  LAB_REAGENTS: "cat.labs",
  REAGENT_TESTS: "cat.reagents",
  REAGENT_TEST_KITS: "cat.purity",
  ANALYTICAL_SCALES: "cat.scales",
  ORGANIC_SOLVENTS: "cat.solvents",
  INDUSTRIAL_ACETONE: "cat.acetone",
  ETHYL_ETHER: "cat.ether",
  DCM_SOLVENT: "cat.dcm",
  LAB_GLASSWARE: "cat.glass",
  DISTILLATION_COLUMNS: "cat.columns",
  BOROSILICATE_FLASKS: "cat.flasks",
  VACUUM_PUMPS: "cat.pumps",
  INFRASTRUCTURE: "cat.servers",
  BULLETPROOF_HOST: "cat.bulletproof",
  OFFSHORE_VPS: "cat.vps",
  BULLETPROOF_DEDICATED: "cat.dedicated",
  DECENTRALIZED_VPS: "cat.decentralized",
  PEER_HOSTING: "cat.hosting",
  ANON_NODE_MGMT: "cat.nodes",
};
